In [1]:
import numpy as np
import pandas as pd
from collections import Counter 
import matplotlib.pyplot as plt
import math

In [2]:
data_business = pd.read_csv(r'D:\yelp_dataset\yelp_dataset~\business.csv',index_col = 0)
data_business.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,CoatCheck,GoodForKids,BusinessParking,Open24Hours,OutdoorSeating,ByAppointmentOnly,DogsAllowed,Caters,RestaurantsReservations,RestaurantsDelivery
0,ljxNT9p0y7YMPx0fcNBGig,Tony's Restaurant & 3rd Street Cafe,312 Piasa St,Alton,IL,62002,38.896563,-90.186203,3.0,94,...,NaN,True,NaN,NaN,True,NaN,NaN,True,True,False
1,EuRGgOwJ0g1vTj2R04j37Q,Crafty Crab,51 Ludwig Dr,Fairview Heights,IL,62208,38.601298,-89.989683,2.5,14,...,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,uYBx50Yl_Jc-UYwFzudBsQ,Chew Doin Fried Chicken & Ramen,210 South Buchanan,Edwardsville,IL,62025,38.810591,-89.952484,3.0,10,...,NaN,NaN,NaN,NaN,False,NaN,NaN,False,False,True
3,zjQDk4tZyhEroyqtkgvx0g,The Cobblestone Eatery and Drinkery,115 W St Louis St,Lebanon,IL,62254,38.604107,-89.808533,3.5,52,...,False,True,NaN,NaN,True,False,False,False,False,False
4,gI34hM-873fwF1XQ8hOaSg,Joe’s Pizza and Pasta,"5775 Godfrey Rd, Ste A",Godfrey,IL,62035,38.949183,-90.190306,4.0,17,...,NaN,NaN,NaN,NaN,True,NaN,NaN,True,True,True

In [3]:
#get frequencies of categories in the dataset
category_frequency = []
num_tags = []

for i in range(data_business.shape[0]):
    each_line = data_business['category'][i].split(", ")
    for content in each_line:
        category_frequency.append(content)
        num_tags.append(len(content))

In [4]:
#count the categories whose frequencies are over 10
new_feature = Counter(category_frequency).most_common(63)

feature = pd.DataFrame()
for ind,val in enumerate(new_feature[2:]):
    feature.loc[ind,'Feature'] = val[0]
    feature.loc[ind,'IDF'] =  math.log1p(len(data_business.business_id) / val[1])

In [5]:
data_business2 = data_business

for ind in range(feature.shape[0]):
    ft = feature.loc[ind,'Feature']
    for i in range(data_business2.shape[0]):
        each_line = data_business2['category'][i].split(", ")
        if ft in each_line:
            data_business2.loc[i,ft] = 1 
        else:
            data_business2.loc[i,ft] = 0

In [6]:
data_business2.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,Buffets,Flowers & Gifts,Discount Store,Gas Stations,Juice Bars & Smoothies,Electronics,Breweries,Home & Garden,Florists,Cupcakes
0,ljxNT9p0y7YMPx0fcNBGig,Tony's Restaurant & 3rd Street Cafe,312 Piasa St,Alton,IL,62002,38.896563,-90.186203,3.0,94,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,EuRGgOwJ0g1vTj2R04j37Q,Crafty Crab,51 Ludwig Dr,Fairview Heights,IL,62208,38.601298,-89.989683,2.5,14,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,uYBx50Yl_Jc-UYwFzudBsQ,Chew Doin Fried Chicken & Ramen,210 South Buchanan,Edwardsville,IL,62025,38.810591,-89.952484,3.0,10,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,zjQDk4tZyhEroyqtkgvx0g,The Cobblestone Eatery and Drinkery,115 W St Louis St,Lebanon,IL,62254,38.604107,-89.808533,3.5,52,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,gI34hM-873fwF1XQ8hOaSg,Joe’s Pizza and Pasta,"5775 Godfrey Rd, Ste A",Godfrey,IL,62035,38.949183,-90.190306,4.0,17,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
data_business2.to_csv(r'D:\yelp_dataset\yelp_dataset~\business_cj.csv')